ALTER TABLE clients ADD COLUMN IF NOT EXISTS display_name VARCHAR(120);
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS display_name VARCHAR(120);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS display_name VARCHAR(120);
ALTER TABLE terminals ADD COLUMN IF NOT EXISTS display_name VARCHAR(120);
ALTER TABLE admins ADD COLUMN IF NOT EXISTS display_name VARCHAR(120);